# Generated by Django 3.1.8 on 2021-06-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='genre',
            new_name='alter_ego_name',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='runtime',
        ),
        migrations.AddField(
            model_name='superhero',
            name='catch_phrase',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superhero',
            name='primary_superhero_ability',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superhero',
            name='secondary_superhero_ability',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
